
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String:      `server=localhost;database=PetaPocoSample;uid=testman;pwd=**zapped**;SslMode=None;`
//     Provider:               `MySql.Data.MySqlClient`
//     Schema:                 ``
//     Include Views:          `True`
//     Genetated:              `2020/03/02 12:38:25`

using System;
using PetaPoco;

namespace PetaPocoAppFx.Database.MySql
{
    /// <summary>
    /// PetaPocoSample 接続文字列
    /// </summary>
    public static class Config
    {
        /// <summary>デフォルトの接続文字列</summary>
        public static string ConnectionString { get; set; }
    }

    /// <summary>
    /// PetaPocoSample Database Object
    /// </summary>
    public class DB : DatabaseExtension
    {
        /// <summary>
        /// PetaPocoSample Database Object
        /// </summary>
        public DB() : base(Config.ConnectionString, DBType.MySql)
        {
        }
    }


    /// <summary>テストテーブル - オートナンバー</summary>
    [TableName("trautonumber")]
    [PrimaryKey("Key03", AutoIncrement=true)]
    [ExplicitColumns]
    public class TrAutoNumber : PetaPoco.PetaPocoRecord<TrAutoNumber>
    {
        /// <summary>プライマリキー</summary>
        [Column] public long Key03 { get { return _Key03; } set { _Key03 = value; MarkColumnModified("Key03"); } } long _Key03;
        /// <summary>varcharの列</summary>
        [Column] public string ColVarchar { get { return _ColVarchar; } set { _ColVarchar = value; MarkColumnModified("ColVarchar"); } } string _ColVarchar;
        /// <summary>charの列</summary>
        [Column] public string ColChar { get { return _ColChar; } set { _ColChar = value; MarkColumnModified("ColChar"); } } string _ColChar;
        /// <summary>bigintの列</summary>
        [Column] public long? ColBigint { get { return _ColBigint; } set { _ColBigint = value; MarkColumnModified("ColBigint"); } } long? _ColBigint;
        /// <summary>intの列</summary>
        [Column] public int? ColInt { get { return _ColInt; } set { _ColInt = value; MarkColumnModified("ColInt"); } } int? _ColInt;
        /// <summary>smallintの列</summary>
        [Column] public short? ColSmallint { get { return _ColSmallint; } set { _ColSmallint = value; MarkColumnModified("ColSmallint"); } } short? _ColSmallint;
        /// <summary>bitの列</summary>
        [Column] public bool ColBool { get { return _ColBool; } set { _ColBool = value; MarkColumnModified("ColBool"); } } bool _ColBool;
        /// <summary>decimalの列</summary>
        [Column] public decimal? ColDecimal { get { return _ColDecimal; } set { _ColDecimal = value; MarkColumnModified("ColDecimal"); } } decimal? _ColDecimal;
        /// <summary>numericの列</summary>
        [Column] public decimal? ColNumeric { get { return _ColNumeric; } set { _ColNumeric = value; MarkColumnModified("ColNumeric"); } } decimal? _ColNumeric;
        /// <summary>dateの列</summary>
        [Column] public DateTime? ColDate { get { return _ColDate; } set { _ColDate = value; MarkColumnModified("ColDate"); } } DateTime? _ColDate;
        /// <summary>timeの列</summary>
        [Column] public TimeSpan? ColTime { get { return _ColTime; } set { _ColTime = value; MarkColumnModified("ColTime"); } } TimeSpan? _ColTime;
        /// <summary>datetimeの列</summary>
        [Column] public DateTime ColTimestamp { get { return _ColTimestamp; } set { _ColTimestamp = value; MarkColumnModified("ColTimestamp"); } } DateTime _ColTimestamp;
        /// <summary>longtextの列</summary>
        [Column] public string ColText { get { return _ColText; } set { _ColText = value; MarkColumnModified("ColText"); } } string _ColText;
        /// <summary>longblobの列</summary>
        [Column] public byte[] ColBytea { get { return _ColBytea; } set { _ColBytea = value; MarkColumnModified("ColBytea"); } } byte[] _ColBytea;
        /// <summary>bigint(UNSIGNED)の列</summary>
        [Column] public ulong? ColUBigint { get { return _ColUBigint; } set { _ColUBigint = value; MarkColumnModified("ColUBigint"); } } ulong? _ColUBigint;
        /// <summary>int(UNSIGNED)の列</summary>
        [Column] public uint? ColUInt { get { return _ColUInt; } set { _ColUInt = value; MarkColumnModified("ColUInt"); } } uint? _ColUInt;
        /// <summary>smallint(UNSIGNED)の列</summary>
        [Column] public ushort? ColUSmallint { get { return _ColUSmallint; } set { _ColUSmallint = value; MarkColumnModified("ColUSmallint"); } } ushort? _ColUSmallint;
        /// <summary>tinyint(UNSIGNED)の列</summary>
        [Column] public byte? ColUTinyInt { get { return _ColUTinyInt; } set { _ColUTinyInt = value; MarkColumnModified("ColUTinyInt"); } } byte? _ColUTinyInt;
    }

    /// <summary>テストテーブル - 複合キー</summary>
    [TableName("trcompositekey")]
    [PrimaryKey("Key01,Key02", AutoIncrement=false)]
    [ExplicitColumns]
    public class TrCompositeKey: PetaPoco.PetaPocoRecord<TrCompositeKey>
    {
        /// <summary>プライマリキーその１</summary>
        [Column] public string Key01 { get { return _Key01; } set { _Key01 = value; MarkColumnModified("Key01"); } } string _Key01;
        /// <summary>プライマリキーその２</summary>
        [Column] public int Key02 { get { return _Key02; } set { _Key02 = value; MarkColumnModified("Key02"); } } int _Key02;
        /// <summary>boolの列</summary>
        [Column] public bool ColBool { get { return _ColBool; } set { _ColBool = value; MarkColumnModified("ColBool"); } } bool _ColBool;
        /// <summary>intの列</summary>
        [Column] public int? ColInt { get { return _ColInt; } set { _ColInt = value; MarkColumnModified("ColInt"); } } int? _ColInt;
        /// <summary>decimalの列</summary>
        [Column] public decimal? ColDec { get { return _ColDec; } set { _ColDec = value; MarkColumnModified("ColDec"); } } decimal? _ColDec;
        /// <summary>varcharの列</summary>
        [Column] public string ColVarchar { get { return _ColVarchar; } set { _ColVarchar = value; MarkColumnModified("ColVarchar"); } } string _ColVarchar;
        /// <summary>更新者</summary>
        [Column] public string UpdateBy { get { return _UpdateBy; } set { _UpdateBy = value; MarkColumnModified("UpdateBy"); } } string _UpdateBy;
        /// <summary>更新日時</summary>
        [Column] public DateTime UpdateDt { get { return _UpdateDt; } set { _UpdateDt = value; MarkColumnModified("UpdateDt"); } } DateTime _UpdateDt;
    }

    /// <summary>VIEW</summary>
    [TableName("vihogefuga")]
    [ExplicitColumns]
    public class ViHogeFuga
    {
        /// <summary>プライマリキーその１</summary>
        [Column] public string Tbl1Key01 { get; set; }
        /// <summary>プライマリキーその２</summary>
        [Column] public int Tbl1Key02 { get; set; }
        /// <summary>boolの列</summary>
        [Column] public bool Tbl1ColBool { get; set; }
        /// <summary>intの列</summary>
        [Column] public int? Tbl1ColInt { get; set; }
        /// <summary>decimalの列</summary>
        [Column] public decimal? Tbl1ColDec { get; set; }
        /// <summary>varcharの列</summary>
        [Column] public string Tbl1ColVarchar { get; set; }
        /// <summary>更新者</summary>
        [Column] public string Tbl1UpdateBy { get; set; }
        /// <summary>更新日時</summary>
        [Column] public DateTime Tbl1UpdateDt { get; set; }
        /// <summary>bitの列</summary>
        [Column] public bool? Tbl2ColBool { get; set; }
        /// <summary>varcharの列</summary>
        [Column] public string Tbl2ColVarchar { get; set; }
        /// <summary>datetimeの列</summary>
        [Column] public DateTime? Tbl2ColTimestamp { get; set; }
    }
}


