
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String:      `Data Source=CentOSdb/XEPDB1;User Id=testman;Password=**zapped**;Pooling=true;`
//     Provider:               `Oracle.DataAccess.Client`
//     Schema:                 ``
//     Include Views:          `True`
//     Genetated:              `2020/03/07 22:16:58`

using System;
using PetaPoco;

namespace PetaPocoAppFx.Database.Oracle
{
    /// <summary>
    /// PetaPocoSample 接続文字列
    /// </summary>
    public static class Config
    {
        /// <summary>デフォルトの接続文字列</summary>
        public static string ConnectionString { get; set; }
    }

    /// <summary>
    /// PetaPocoSample Database Object
    /// </summary>
    public class DB : DatabaseExtension
    {
        /// <summary>
        /// PetaPocoSample Database Object
        /// </summary>
        public DB() : base(Config.ConnectionString, DBType.Oracle)
        {
        }
    }


    /// <summary>テストテーブル - オートナンバー</summary>
    [TableName("TR_AUTO_NUMBER")]
    [PrimaryKey("KEY03", AutoIncrement=true)]
    [ExplicitColumns]
    public class TrAutoNumber: PetaPoco.PetaPocoRecord<TrAutoNumber>
    {
        /// <summary>オートナンバーキー</summary>
        [Column("KEY03")] public decimal Key03 { get { return _Key03; } set { _Key03 = value; MarkColumnModified("KEY03"); } } decimal _Key03;
        /// <summary>プライマリキーその１</summary>
        [Column("KEY01")] public string Key01 { get { return _Key01; } set { _Key01 = value; MarkColumnModified("KEY01"); } } string _Key01;
        /// <summary>int型の列</summary>
        [Column("COL_INT")] public decimal? ColInt { get { return _ColInt; } set { _ColInt = value; MarkColumnModified("COL_INT"); } } decimal? _ColInt;
    }

    /// <summary>テストテーブル - 列の型テスト</summary>
    [TableName("TR_COLUMNS")]
    [PrimaryKey("KEY01", AutoIncrement=false)]
    [ExplicitColumns]
    public class TrColumn: PetaPoco.PetaPocoRecord<TrColumn>
    {
        /// <summary>プライマリキーその１</summary>
        [Column("KEY01")] public string Key01 { get { return _Key01; } set { _Key01 = value; MarkColumnModified("KEY01"); } } string _Key01;
        /// <summary>number(10,3)の列</summary>
        [Column("COL_NUMBER")] public decimal? ColNumber { get { return _ColNumber; } set { _ColNumber = value; MarkColumnModified("COL_NUMBER"); } } decimal? _ColNumber;
        /// <summary>number(5)の列</summary>
        [Column("COL_NUMBER5")] public decimal? ColNumber5 { get { return _ColNumber5; } set { _ColNumber5 = value; MarkColumnModified("COL_NUMBER5"); } } decimal? _ColNumber5;
        /// <summary>char(5)の列</summary>
        [Column("COL_CHAR")] public string ColChar { get { return _ColChar; } set { _ColChar = value; MarkColumnModified("COL_CHAR"); } } string _ColChar;
        /// <summary>nchar(5)の列</summary>
        [Column("COL_NCHAR")] public string ColNchar { get { return _ColNchar; } set { _ColNchar = value; MarkColumnModified("COL_NCHAR"); } } string _ColNchar;
        /// <summary>varchar2(50)の列</summary>
        [Column("COL_VARCHAR2")] public string ColVarchar2 { get { return _ColVarchar2; } set { _ColVarchar2 = value; MarkColumnModified("COL_VARCHAR2"); } } string _ColVarchar2;
        /// <summary>nvarchar2(50)の列</summary>
        [Column("COL_NVARCHAR2")] public string ColNvarchar2 { get { return _ColNvarchar2; } set { _ColNvarchar2 = value; MarkColumnModified("COL_NVARCHAR2"); } } string _ColNvarchar2;
        /// <summary>dateの列</summary>
        [Column("COL_DATE")] public DateTime ColDate { get { return _ColDate; } set { _ColDate = value; MarkColumnModified("COL_DATE"); } } DateTime _ColDate;
        /// <summary>timestampの列</summary>
        [Column("COL_TIMESTAMP")] public DateTime ColTimestamp { get { return _ColTimestamp; } set { _ColTimestamp = value; MarkColumnModified("COL_TIMESTAMP"); } } DateTime _ColTimestamp;
        /// <summary>binary_floatの列</summary>
        [Column("COL_BINARY_FLOAT")] public float? ColBinaryFloat { get { return _ColBinaryFloat; } set { _ColBinaryFloat = value; MarkColumnModified("COL_BINARY_FLOAT"); } } float? _ColBinaryFloat;
        /// <summary>binary_doubleの列</summary>
        [Column("COL_BINARY_DOUBLE")] public double? ColBinaryDouble { get { return _ColBinaryDouble; } set { _ColBinaryDouble = value; MarkColumnModified("COL_BINARY_DOUBLE"); } } double? _ColBinaryDouble;
        /// <summary>raw(1024)の列</summary>
        [Column("COL_RAW")] public byte[] ColRaw { get { return _ColRaw; } set { _ColRaw = value; MarkColumnModified("COL_RAW"); } } byte[] _ColRaw;
        /// <summary>long rawの列</summary>
        [Column("COL_LONG_RAW")] public byte[] ColLongRaw { get { return _ColLongRaw; } set { _ColLongRaw = value; MarkColumnModified("COL_LONG_RAW"); } } byte[] _ColLongRaw;
        /// <summary>blobの列</summary>
        [Column("COL_BLOB")] public byte[] ColBlob { get { return _ColBlob; } set { _ColBlob = value; MarkColumnModified("COL_BLOB"); } } byte[] _ColBlob;
    }

    /// <summary>テストテーブル - 複合キー</summary>
    [TableName("TR_COMPOSITE_KEY")]
    [PrimaryKey("KEY01,KEY02", AutoIncrement=false)]
    [ExplicitColumns]
    public class TrCompositeKey: PetaPoco.PetaPocoRecord<TrCompositeKey>
    {
        /// <summary>プライマリキーその１</summary>
        [Column("KEY01")] public string Key01 { get { return _Key01; } set { _Key01 = value; MarkColumnModified("KEY01"); } } string _Key01;
        /// <summary>プライマリキーその２</summary>
        [Column("KEY02")] public decimal Key02 { get { return _Key02; } set { _Key02 = value; MarkColumnModified("KEY02"); } } decimal _Key02;
        /// <summary>bool型の列</summary>
        [Column("COL_BOOL")] public decimal ColBool { get { return _ColBool; } set { _ColBool = value; MarkColumnModified("COL_BOOL"); } } decimal _ColBool;
        /// <summary>int型の列</summary>
        [Column("COL_INT")] public int? ColInt { get { return _ColInt; } set { _ColInt = value; MarkColumnModified("COL_INT"); } } int? _ColInt;
        /// <summary>decimal型の列</summary>
        [Column("COL_DEC")] public double? ColDec { get { return _ColDec; } set { _ColDec = value; MarkColumnModified("COL_DEC"); } } double? _ColDec;
        /// <summary>varchar型の列</summary>
        [Column("COL_VARCHAR")] public string ColVarchar { get { return _ColVarchar; } set { _ColVarchar = value; MarkColumnModified("COL_VARCHAR"); } } string _ColVarchar;
        /// <summary>作成者</summary>
        [Column("CREATE_BY")] public string CreateBy { get { return _CreateBy; } set { _CreateBy = value; MarkColumnModified("CREATE_BY"); } } string _CreateBy;
        /// <summary>作成日時</summary>
        [Column("CREATE_DT")] public DateTime CreateDt { get { return _CreateDt; } set { _CreateDt = value; MarkColumnModified("CREATE_DT"); } } DateTime _CreateDt;
        /// <summary>更新者</summary>
        [Column("UPDATE_BY")] public string UpdateBy { get { return _UpdateBy; } set { _UpdateBy = value; MarkColumnModified("UPDATE_BY"); } } string _UpdateBy;
        /// <summary>更新日時</summary>
        [Column("UPDATE_DT")] public DateTime UpdateDt { get { return _UpdateDt; } set { _UpdateDt = value; MarkColumnModified("UPDATE_DT"); } } DateTime _UpdateDt;
    }

    /// <summary>テストビュー その1</summary>
    [TableName("VI_HOGE_FUGA")]
    [ExplicitColumns]
    public class ViHogeFuga
    {
        /// <summary>ほげ</summary>
        [Column("TBL1_KEY01")] public string Tbl1Key01 { get; set; }
        /// <summary>ふが</summary>
        [Column("TBL1_KEY02")] public decimal Tbl1Key02 { get; set; }
        /// <summary></summary>
        [Column("TBL1_COL_BOOL")] public decimal Tbl1ColBool { get; set; }
        /// <summary></summary>
        [Column("TBL1_COL_INT")] public decimal? Tbl1ColInt { get; set; }
        /// <summary></summary>
        [Column("TBL1_COL_DEC")] public decimal? Tbl1ColDec { get; set; }
        /// <summary></summary>
        [Column("TBL1_COL_VARCHAR")] public string Tbl1ColVarchar { get; set; }
        /// <summary></summary>
        [Column("TBL1_UPDATE_BY")] public string Tbl1UpdateBy { get; set; }
        /// <summary></summary>
        [Column("TBL1_UPDATE_DT")] public DateTime Tbl1UpdateDt { get; set; }
        /// <summary></summary>
        [Column("TBL2_COL_INT")] public decimal? Tbl2ColInt { get; set; }
    }
}


