
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String:      `Data Source=localhost;Database=PetaPocoSample;Integrated Security=False;User ID=testman;Password=**zapped**;Pooling=true;`
//     Provider:               `System.Data.SqlClient`
//     Schema:                 ``
//     Include Views:          `True`
//     Genetated:              `2020/03/27 15:48:00`

using System;
using PetaPoco;

namespace PetaPocoAppFx.Database.SQLServer
{
    /// <summary>
    /// PetaPocoSample 接続文字列
    /// </summary>
    public static class Config
    {
        /// <summary>デフォルトの接続文字列</summary>
        public static string ConnectionString { get; set; }
    }

    /// <summary>
    /// PetaPocoSample Database Object
    /// </summary>
    public class DB : DatabaseExtension
    {
        /// <summary>
        /// PetaPocoSample Database Object
        /// </summary>
        public DB() : base(Config.ConnectionString, RDBType.SqlServer)
        {
        }
    }


    /// <summary>テストテーブル - オートナンバー</summary>
    [TableName("TrAutoNumber")]
    [PrimaryKey("Key03", AutoIncrement=true)]
    [ExplicitColumns]
    public class TrAutoNumber: PetaPoco.PetaPocoRecord<TrAutoNumber>
    {
        /// <summary>オートナンバーキー</summary>
        [Column] public int Key03 { get { return _Key03; } set { _Key03 = value; MarkColumnModified("Key03"); } } int _Key03;
        /// <summary>プライマリキーその１</summary>
        [Column] public string Key01 { get { return _Key01; } set { _Key01 = value; MarkColumnModified("Key01"); } } string _Key01;
        /// <summary>int型の列</summary>
        [Column] public int? ColInt { get { return _ColInt; } set { _ColInt = value; MarkColumnModified("ColInt"); } } int? _ColInt;
    }

    /// <summary>TrColumns</summary>
    [TableName("TrColumns")]
    [PrimaryKey("Key01", AutoIncrement=false)]
    [ExplicitColumns]
    public class TrColumn: PetaPoco.PetaPocoRecord<TrColumn>
    {
        /// <summary>プライマリキー</summary>
        [Column] public string Key01 { get { return _Key01; } set { _Key01 = value; MarkColumnModified("Key01"); } } string _Key01;
        /// <summary>bigintの列</summary>
        [Column] public long? ColBigint { get { return _ColBigint; } set { _ColBigint = value; MarkColumnModified("ColBigint"); } } long? _ColBigint;
        /// <summary>intの列</summary>
        [Column] public int? ColInt { get { return _ColInt; } set { _ColInt = value; MarkColumnModified("ColInt"); } } int? _ColInt;
        /// <summary>smallintの列</summary>
        [Column] public short? ColSmallint { get { return _ColSmallint; } set { _ColSmallint = value; MarkColumnModified("ColSmallint"); } } short? _ColSmallint;
        /// <summary>tinyintの列</summary>
        [Column] public byte? ColTinyint { get { return _ColTinyint; } set { _ColTinyint = value; MarkColumnModified("ColTinyint"); } } byte? _ColTinyint;
        /// <summary>bitの列</summary>
        [Column] public bool ColBool { get { return _ColBool; } set { _ColBool = value; MarkColumnModified("ColBool"); } } bool _ColBool;
        /// <summary>decimal(14,2)の列</summary>
        [Column] public decimal? ColDecimal { get { return _ColDecimal; } set { _ColDecimal = value; MarkColumnModified("ColDecimal"); } } decimal? _ColDecimal;
        /// <summary>realの列</summary>
        [Column] public float? ColFloat { get { return _ColFloat; } set { _ColFloat = value; MarkColumnModified("ColFloat"); } } float? _ColFloat;
        /// <summary>floatの列</summary>
        [Column] public double? ColDouble { get { return _ColDouble; } set { _ColDouble = value; MarkColumnModified("ColDouble"); } } double? _ColDouble;
        /// <summary>dateの列</summary>
        [Column] public DateTime? ColDate { get { return _ColDate; } set { _ColDate = value; MarkColumnModified("ColDate"); } } DateTime? _ColDate;
        /// <summary>timeの列</summary>
        [Column] public TimeSpan? ColTime { get { return _ColTime; } set { _ColTime = value; MarkColumnModified("ColTime"); } } TimeSpan? _ColTime;
        /// <summary>datetime2の列</summary>
        [Column] public DateTime? ColDateTime { get { return _ColDateTime; } set { _ColDateTime = value; MarkColumnModified("ColDateTime"); } } DateTime? _ColDateTime;
        /// <summary>nchar(5)の列</summary>
        [Column] public string ColChar { get { return _ColChar; } set { _ColChar = value; MarkColumnModified("ColChar"); } } string _ColChar;
        /// <summary>nvarchar(255)の列</summary>
        [Column] public string ColVarchar { get { return _ColVarchar; } set { _ColVarchar = value; MarkColumnModified("ColVarchar"); } } string _ColVarchar;
        /// <summary>ntextの列</summary>
        [Column] public string ColText { get { return _ColText; } set { _ColText = value; MarkColumnModified("ColText"); } } string _ColText;
        /// <summary>imageの列</summary>
        [Column] public byte[] ColBlob { get { return _ColBlob; } set { _ColBlob = value; MarkColumnModified("ColBlob"); } } byte[] _ColBlob;
        /// <summary>numeric(13,3)の列</summary>
        [Column] public decimal? ColNumeric { get { return _ColNumeric; } set { _ColNumeric = value; MarkColumnModified("ColNumeric"); } } decimal? _ColNumeric;
        /// <summary>moneyの列</summary>
        [Column] public decimal? ColMoney { get { return _ColMoney; } set { _ColMoney = value; MarkColumnModified("ColMoney"); } } decimal? _ColMoney;
        /// <summary>datetimeの列</summary>
        [Column] public DateTime? ColDateTimePast { get { return _ColDateTimePast; } set { _ColDateTimePast = value; MarkColumnModified("ColDateTimePast"); } } DateTime? _ColDateTimePast;
        /// <summary>smalldatetimeの列</summary>
        [Column] public DateTime? ColSmallDateTime { get { return _ColSmallDateTime; } set { _ColSmallDateTime = value; MarkColumnModified("ColSmallDateTime"); } } DateTime? _ColSmallDateTime;
        /// <summary>char(5)の列</summary>
        [Column] public string ColCharPast { get { return _ColCharPast; } set { _ColCharPast = value; MarkColumnModified("ColCharPast"); } } string _ColCharPast;
        /// <summary>varchar(50)の列</summary>
        [Column] public string ColVarCharPast { get { return _ColVarCharPast; } set { _ColVarCharPast = value; MarkColumnModified("ColVarCharPast"); } } string _ColVarCharPast;
        /// <summary>textの列</summary>
        [Column] public string ColTextPast { get { return _ColTextPast; } set { _ColTextPast = value; MarkColumnModified("ColTextPast"); } } string _ColTextPast;
        /// <summary>varbinaryの列</summary>
        [Column] public byte[] ColVarBinary { get { return _ColVarBinary; } set { _ColVarBinary = value; MarkColumnModified("ColVarBinary"); } } byte[] _ColVarBinary;
    }

    /// <summary>テストテーブル - 複合キー</summary>
    [TableName("TrCompositeKey")]
    [PrimaryKey("Key01,Key02", AutoIncrement=false)]
    [ExplicitColumns]
    public class TrCompositeKey: PetaPoco.PetaPocoRecord<TrCompositeKey>
    {
        /// <summary>プライマリキーその１</summary>
        [Column] public string Key01 { get { return _Key01; } set { _Key01 = value; MarkColumnModified("Key01"); } } string _Key01;
        /// <summary>プライマリキーその２</summary>
        [Column] public int Key02 { get { return _Key02; } set { _Key02 = value; MarkColumnModified("Key02"); } } int _Key02;
        /// <summary>bit型の列</summary>
        [Column] public bool ColBool { get { return _ColBool; } set { _ColBool = value; MarkColumnModified("ColBool"); } } bool _ColBool;
        /// <summary>int型の列</summary>
        [Column] public int? ColInt { get { return _ColInt; } set { _ColInt = value; MarkColumnModified("ColInt"); } } int? _ColInt;
        /// <summary>decimal型の列</summary>
        [Column] public decimal? ColDec { get { return _ColDec; } set { _ColDec = value; MarkColumnModified("ColDec"); } } decimal? _ColDec;
        /// <summary>varchar型の列</summary>
        [Column] public string ColVarchar { get { return _ColVarchar; } set { _ColVarchar = value; MarkColumnModified("ColVarchar"); } } string _ColVarchar;
        /// <summary>作成者</summary>
        [Column] public string CreateBy { get { return _CreateBy; } set { _CreateBy = value; MarkColumnModified("CreateBy"); } } string _CreateBy;
        /// <summary>作成日時</summary>
        [Column] public DateTime CreateDt { get { return _CreateDt; } set { _CreateDt = value; MarkColumnModified("CreateDt"); } } DateTime _CreateDt;
        /// <summary>更新者</summary>
        [Column] public string UpdateBy { get { return _UpdateBy; } set { _UpdateBy = value; MarkColumnModified("UpdateBy"); } } string _UpdateBy;
        /// <summary>更新日時</summary>
        [Column] public DateTime UpdateDt { get { return _UpdateDt; } set { _UpdateDt = value; MarkColumnModified("UpdateDt"); } } DateTime _UpdateDt;
    }

    /// <summary>テストビュー その1</summary>
    [TableName("ViHogeFuga")]
    [ExplicitColumns]
    public class ViHogeFuga
    {
        /// <summary></summary>
        [Column] public string Tbl1Key01 { get; set; }
        /// <summary></summary>
        [Column] public int Tbl1Key02 { get; set; }
        /// <summary></summary>
        [Column] public bool Tbl1ColBool { get; set; }
        /// <summary></summary>
        [Column] public int? Tbl1ColInt { get; set; }
        /// <summary></summary>
        [Column] public decimal? Tbl1ColDec { get; set; }
        /// <summary></summary>
        [Column] public string Tbl1ColVarchar { get; set; }
        /// <summary></summary>
        [Column] public string Tbl1UpdateBy { get; set; }
        /// <summary></summary>
        [Column] public DateTime Tbl1UpdateDt { get; set; }
        /// <summary></summary>
        [Column] public int? Tbl2ColInt { get; set; }
    }
}


