
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String:      `Server=192.168.1.212;Port=5432;Database=dvdrental;Encoding=UTF8;User Id=testman;Password=**zapped**;`
//     Provider:               `Npgsql`
//     Schema:                 ``
//     Include Views:          `True`
//     Genetated:              `2020/02/24 16:18:51`

using System;
using PetaPoco;

namespace PetaPoco4Core.Database.DvdRental
{
    /// <summary>
    /// dvdrental 接続文字列
    /// </summary>
    public static class Config
    {
        /// <summary>デフォルトの接続文字列</summary>
        public static string ConnectionString { get; set; }
    }

    /// <summary>
    /// dvdrental Database Object
    /// </summary>
    public class DB : DatabaseExtension
    {
        /// <summary>
        /// dvdrental Database Object
        /// </summary>
        public DB() : base(Config.ConnectionString, "Npgsql")
        {
        }
    }


    /// <summary></summary>
    [TableName("actor")]
    [PrimaryKey("actor_id", AutoIncrement=true, SequenceName="actor_actor_id_seq")]
    [ExplicitColumns]
    public class Actor: PetaPoco.PetaPocoRecord<Actor>
    {
        /// <summary></summary>
        [Column("actor_id")] public int ActorId { get { return _ActorId; } set { _ActorId = value; MarkColumnModified("actor_id"); } } int _ActorId;
        /// <summary></summary>
        [Column("first_name")] public string FirstName { get { return _FirstName; } set { _FirstName = value; MarkColumnModified("first_name"); } } string _FirstName;
        /// <summary></summary>
        [Column("last_name")] public string LastName { get { return _LastName; } set { _LastName = value; MarkColumnModified("last_name"); } } string _LastName;
        /// <summary></summary>
        [Column("last_update")] public DateTime LastUpdate { get { return _LastUpdate; } set { _LastUpdate = value; MarkColumnModified("last_update"); } } DateTime _LastUpdate;
    }

    /// <summary></summary>
    [TableName("address")]
    [PrimaryKey("address_id", AutoIncrement=true, SequenceName="address_address_id_seq")]
    [ExplicitColumns]
    public class Address: PetaPoco.PetaPocoRecord<Address>
    {
        /// <summary></summary>
        [Column("address_id")] public int AddressId { get { return _AddressId; } set { _AddressId = value; MarkColumnModified("address_id"); } } int _AddressId;
        /// <summary></summary>
        [Column("address")] public string _Address { get { return __Address; } set { __Address = value; MarkColumnModified("address"); } } string __Address;
        /// <summary></summary>
        [Column("address2")] public string Address2 { get { return _Address2; } set { _Address2 = value; MarkColumnModified("address2"); } } string _Address2;
        /// <summary></summary>
        [Column("district")] public string District { get { return _District; } set { _District = value; MarkColumnModified("district"); } } string _District;
        /// <summary></summary>
        [Column("city_id")] public short CityId { get { return _CityId; } set { _CityId = value; MarkColumnModified("city_id"); } } short _CityId;
        /// <summary></summary>
        [Column("postal_code")] public string PostalCode { get { return _PostalCode; } set { _PostalCode = value; MarkColumnModified("postal_code"); } } string _PostalCode;
        /// <summary></summary>
        [Column("phone")] public string Phone { get { return _Phone; } set { _Phone = value; MarkColumnModified("phone"); } } string _Phone;
        /// <summary></summary>
        [Column("last_update")] public DateTime LastUpdate { get { return _LastUpdate; } set { _LastUpdate = value; MarkColumnModified("last_update"); } } DateTime _LastUpdate;
    }

    /// <summary></summary>
    [TableName("category")]
    [PrimaryKey("category_id", AutoIncrement=true, SequenceName="category_category_id_seq")]
    [ExplicitColumns]
    public class Category: PetaPoco.PetaPocoRecord<Category>
    {
        /// <summary></summary>
        [Column("category_id")] public int CategoryId { get { return _CategoryId; } set { _CategoryId = value; MarkColumnModified("category_id"); } } int _CategoryId;
        /// <summary></summary>
        [Column("name")] public string Name { get { return _Name; } set { _Name = value; MarkColumnModified("name"); } } string _Name;
        /// <summary></summary>
        [Column("last_update")] public DateTime LastUpdate { get { return _LastUpdate; } set { _LastUpdate = value; MarkColumnModified("last_update"); } } DateTime _LastUpdate;
    }

    /// <summary></summary>
    [TableName("city")]
    [PrimaryKey("city_id", AutoIncrement=true, SequenceName="city_city_id_seq")]
    [ExplicitColumns]
    public class City: PetaPoco.PetaPocoRecord<City>
    {
        /// <summary></summary>
        [Column("city_id")] public int CityId { get { return _CityId; } set { _CityId = value; MarkColumnModified("city_id"); } } int _CityId;
        /// <summary></summary>
        [Column("city")] public string _City { get { return __City; } set { __City = value; MarkColumnModified("city"); } } string __City;
        /// <summary></summary>
        [Column("country_id")] public short CountryId { get { return _CountryId; } set { _CountryId = value; MarkColumnModified("country_id"); } } short _CountryId;
        /// <summary></summary>
        [Column("last_update")] public DateTime LastUpdate { get { return _LastUpdate; } set { _LastUpdate = value; MarkColumnModified("last_update"); } } DateTime _LastUpdate;
    }

    /// <summary></summary>
    [TableName("country")]
    [PrimaryKey("country_id", AutoIncrement=true, SequenceName="country_country_id_seq")]
    [ExplicitColumns]
    public class Country: PetaPoco.PetaPocoRecord<Country>
    {
        /// <summary></summary>
        [Column("country_id")] public int CountryId { get { return _CountryId; } set { _CountryId = value; MarkColumnModified("country_id"); } } int _CountryId;
        /// <summary></summary>
        [Column("country")] public string _Country { get { return __Country; } set { __Country = value; MarkColumnModified("country"); } } string __Country;
        /// <summary></summary>
        [Column("last_update")] public DateTime LastUpdate { get { return _LastUpdate; } set { _LastUpdate = value; MarkColumnModified("last_update"); } } DateTime _LastUpdate;
    }

    /// <summary></summary>
    [TableName("customer")]
    [PrimaryKey("customer_id", AutoIncrement=true, SequenceName="customer_customer_id_seq")]
    [ExplicitColumns]
    public class Customer: PetaPoco.PetaPocoRecord<Customer>
    {
        /// <summary></summary>
        [Column("customer_id")] public int CustomerId { get { return _CustomerId; } set { _CustomerId = value; MarkColumnModified("customer_id"); } } int _CustomerId;
        /// <summary></summary>
        [Column("store_id")] public short StoreId { get { return _StoreId; } set { _StoreId = value; MarkColumnModified("store_id"); } } short _StoreId;
        /// <summary></summary>
        [Column("first_name")] public string FirstName { get { return _FirstName; } set { _FirstName = value; MarkColumnModified("first_name"); } } string _FirstName;
        /// <summary></summary>
        [Column("last_name")] public string LastName { get { return _LastName; } set { _LastName = value; MarkColumnModified("last_name"); } } string _LastName;
        /// <summary></summary>
        [Column("email")] public string Email { get { return _Email; } set { _Email = value; MarkColumnModified("email"); } } string _Email;
        /// <summary></summary>
        [Column("address_id")] public short AddressId { get { return _AddressId; } set { _AddressId = value; MarkColumnModified("address_id"); } } short _AddressId;
        /// <summary></summary>
        [Column("activebool")] public bool Activebool { get { return _Activebool; } set { _Activebool = value; MarkColumnModified("activebool"); } } bool _Activebool;
        /// <summary></summary>
        [Column("create_date")] public DateTime CreateDate { get { return _CreateDate; } set { _CreateDate = value; MarkColumnModified("create_date"); } } DateTime _CreateDate;
        /// <summary></summary>
        [Column("last_update")] public DateTime? LastUpdate { get { return _LastUpdate; } set { _LastUpdate = value; MarkColumnModified("last_update"); } } DateTime? _LastUpdate;
        /// <summary></summary>
        [Column("active")] public int? Active { get { return _Active; } set { _Active = value; MarkColumnModified("active"); } } int? _Active;
    }

    /// <summary></summary>
    [TableName("film")]
    [PrimaryKey("film_id", AutoIncrement=true, SequenceName="film_film_id_seq")]
    [ExplicitColumns]
    public class Film: PetaPoco.PetaPocoRecord<Film>
    {
        /// <summary></summary>
        [Column("film_id")] public int FilmId { get { return _FilmId; } set { _FilmId = value; MarkColumnModified("film_id"); } } int _FilmId;
        /// <summary></summary>
        [Column("title")] public string Title { get { return _Title; } set { _Title = value; MarkColumnModified("title"); } } string _Title;
        /// <summary></summary>
        [Column("description")] public string Description { get { return _Description; } set { _Description = value; MarkColumnModified("description"); } } string _Description;
        /// <summary></summary>
        [Column("release_year")] public int? ReleaseYear { get { return _ReleaseYear; } set { _ReleaseYear = value; MarkColumnModified("release_year"); } } int? _ReleaseYear;
        /// <summary></summary>
        [Column("language_id")] public short LanguageId { get { return _LanguageId; } set { _LanguageId = value; MarkColumnModified("language_id"); } } short _LanguageId;
        /// <summary></summary>
        [Column("rental_duration")] public short RentalDuration { get { return _RentalDuration; } set { _RentalDuration = value; MarkColumnModified("rental_duration"); } } short _RentalDuration;
        /// <summary></summary>
        [Column("rental_rate")] public decimal RentalRate { get { return _RentalRate; } set { _RentalRate = value; MarkColumnModified("rental_rate"); } } decimal _RentalRate;
        /// <summary></summary>
        [Column("length")] public short? Length { get { return _Length; } set { _Length = value; MarkColumnModified("length"); } } short? _Length;
        /// <summary></summary>
        [Column("replacement_cost")] public decimal ReplacementCost { get { return _ReplacementCost; } set { _ReplacementCost = value; MarkColumnModified("replacement_cost"); } } decimal _ReplacementCost;
        /// <summary></summary>
        [Column("rating")] public string Rating { get { return _Rating; } set { _Rating = value; MarkColumnModified("rating"); } } string _Rating;
        /// <summary></summary>
        [Column("last_update")] public DateTime LastUpdate { get { return _LastUpdate; } set { _LastUpdate = value; MarkColumnModified("last_update"); } } DateTime _LastUpdate;
        /// <summary></summary>
        [Column("special_features")] public string SpecialFeatures { get { return _SpecialFeatures; } set { _SpecialFeatures = value; MarkColumnModified("special_features"); } } string _SpecialFeatures;
        /// <summary></summary>
        [Column("fulltext")] public string Fulltext { get { return _Fulltext; } set { _Fulltext = value; MarkColumnModified("fulltext"); } } string _Fulltext;
    }

    /// <summary></summary>
    [TableName("film_actor")]
    [PrimaryKey("actor_id,film_id", AutoIncrement=false)]
    [ExplicitColumns]
    public class FilmActor: PetaPoco.PetaPocoRecord<FilmActor>
    {
        /// <summary></summary>
        [Column("actor_id")] public short ActorId { get { return _ActorId; } set { _ActorId = value; MarkColumnModified("actor_id"); } } short _ActorId;
        /// <summary></summary>
        [Column("film_id")] public short FilmId { get { return _FilmId; } set { _FilmId = value; MarkColumnModified("film_id"); } } short _FilmId;
        /// <summary></summary>
        [Column("last_update")] public DateTime LastUpdate { get { return _LastUpdate; } set { _LastUpdate = value; MarkColumnModified("last_update"); } } DateTime _LastUpdate;
    }

    /// <summary></summary>
    [TableName("film_category")]
    [PrimaryKey("film_id,category_id", AutoIncrement=false)]
    [ExplicitColumns]
    public class FilmCategory: PetaPoco.PetaPocoRecord<FilmCategory>
    {
        /// <summary></summary>
        [Column("film_id")] public short FilmId { get { return _FilmId; } set { _FilmId = value; MarkColumnModified("film_id"); } } short _FilmId;
        /// <summary></summary>
        [Column("category_id")] public short CategoryId { get { return _CategoryId; } set { _CategoryId = value; MarkColumnModified("category_id"); } } short _CategoryId;
        /// <summary></summary>
        [Column("last_update")] public DateTime LastUpdate { get { return _LastUpdate; } set { _LastUpdate = value; MarkColumnModified("last_update"); } } DateTime _LastUpdate;
    }

    /// <summary></summary>
    [TableName("inventory")]
    [PrimaryKey("inventory_id", AutoIncrement=true, SequenceName="inventory_inventory_id_seq")]
    [ExplicitColumns]
    public class Inventory: PetaPoco.PetaPocoRecord<Inventory>
    {
        /// <summary></summary>
        [Column("inventory_id")] public int InventoryId { get { return _InventoryId; } set { _InventoryId = value; MarkColumnModified("inventory_id"); } } int _InventoryId;
        /// <summary></summary>
        [Column("film_id")] public short FilmId { get { return _FilmId; } set { _FilmId = value; MarkColumnModified("film_id"); } } short _FilmId;
        /// <summary></summary>
        [Column("store_id")] public short StoreId { get { return _StoreId; } set { _StoreId = value; MarkColumnModified("store_id"); } } short _StoreId;
        /// <summary></summary>
        [Column("last_update")] public DateTime LastUpdate { get { return _LastUpdate; } set { _LastUpdate = value; MarkColumnModified("last_update"); } } DateTime _LastUpdate;
    }

    /// <summary></summary>
    [TableName("language")]
    [PrimaryKey("language_id", AutoIncrement=true, SequenceName="language_language_id_seq")]
    [ExplicitColumns]
    public class Language: PetaPoco.PetaPocoRecord<Language>
    {
        /// <summary></summary>
        [Column("language_id")] public int LanguageId { get { return _LanguageId; } set { _LanguageId = value; MarkColumnModified("language_id"); } } int _LanguageId;
        /// <summary></summary>
        [Column("name")] public string Name { get { return _Name; } set { _Name = value; MarkColumnModified("name"); } } string _Name;
        /// <summary></summary>
        [Column("last_update")] public DateTime LastUpdate { get { return _LastUpdate; } set { _LastUpdate = value; MarkColumnModified("last_update"); } } DateTime _LastUpdate;
    }

    /// <summary></summary>
    [TableName("payment")]
    [PrimaryKey("payment_id", AutoIncrement=true, SequenceName="payment_payment_id_seq")]
    [ExplicitColumns]
    public class Payment: PetaPoco.PetaPocoRecord<Payment>
    {
        /// <summary></summary>
        [Column("payment_id")] public int PaymentId { get { return _PaymentId; } set { _PaymentId = value; MarkColumnModified("payment_id"); } } int _PaymentId;
        /// <summary></summary>
        [Column("customer_id")] public short CustomerId { get { return _CustomerId; } set { _CustomerId = value; MarkColumnModified("customer_id"); } } short _CustomerId;
        /// <summary></summary>
        [Column("staff_id")] public short StaffId { get { return _StaffId; } set { _StaffId = value; MarkColumnModified("staff_id"); } } short _StaffId;
        /// <summary></summary>
        [Column("rental_id")] public int RentalId { get { return _RentalId; } set { _RentalId = value; MarkColumnModified("rental_id"); } } int _RentalId;
        /// <summary></summary>
        [Column("amount")] public decimal Amount { get { return _Amount; } set { _Amount = value; MarkColumnModified("amount"); } } decimal _Amount;
        /// <summary></summary>
        [Column("payment_date")] public DateTime PaymentDate { get { return _PaymentDate; } set { _PaymentDate = value; MarkColumnModified("payment_date"); } } DateTime _PaymentDate;
    }

    /// <summary></summary>
    [TableName("rental")]
    [PrimaryKey("rental_id", AutoIncrement=true, SequenceName="rental_rental_id_seq")]
    [ExplicitColumns]
    public class Rental: PetaPoco.PetaPocoRecord<Rental>
    {
        /// <summary></summary>
        [Column("rental_id")] public int RentalId { get { return _RentalId; } set { _RentalId = value; MarkColumnModified("rental_id"); } } int _RentalId;
        /// <summary></summary>
        [Column("rental_date")] public DateTime RentalDate { get { return _RentalDate; } set { _RentalDate = value; MarkColumnModified("rental_date"); } } DateTime _RentalDate;
        /// <summary></summary>
        [Column("inventory_id")] public int InventoryId { get { return _InventoryId; } set { _InventoryId = value; MarkColumnModified("inventory_id"); } } int _InventoryId;
        /// <summary></summary>
        [Column("customer_id")] public short CustomerId { get { return _CustomerId; } set { _CustomerId = value; MarkColumnModified("customer_id"); } } short _CustomerId;
        /// <summary></summary>
        [Column("return_date")] public DateTime? ReturnDate { get { return _ReturnDate; } set { _ReturnDate = value; MarkColumnModified("return_date"); } } DateTime? _ReturnDate;
        /// <summary></summary>
        [Column("staff_id")] public short StaffId { get { return _StaffId; } set { _StaffId = value; MarkColumnModified("staff_id"); } } short _StaffId;
        /// <summary></summary>
        [Column("last_update")] public DateTime LastUpdate { get { return _LastUpdate; } set { _LastUpdate = value; MarkColumnModified("last_update"); } } DateTime _LastUpdate;
    }

    /// <summary></summary>
    [TableName("staff")]
    [PrimaryKey("staff_id", AutoIncrement=true, SequenceName="staff_staff_id_seq")]
    [ExplicitColumns]
    public class Staff: PetaPoco.PetaPocoRecord<Staff>
    {
        /// <summary></summary>
        [Column("staff_id")] public int StaffId { get { return _StaffId; } set { _StaffId = value; MarkColumnModified("staff_id"); } } int _StaffId;
        /// <summary></summary>
        [Column("first_name")] public string FirstName { get { return _FirstName; } set { _FirstName = value; MarkColumnModified("first_name"); } } string _FirstName;
        /// <summary></summary>
        [Column("last_name")] public string LastName { get { return _LastName; } set { _LastName = value; MarkColumnModified("last_name"); } } string _LastName;
        /// <summary></summary>
        [Column("address_id")] public short AddressId { get { return _AddressId; } set { _AddressId = value; MarkColumnModified("address_id"); } } short _AddressId;
        /// <summary></summary>
        [Column("email")] public string Email { get { return _Email; } set { _Email = value; MarkColumnModified("email"); } } string _Email;
        /// <summary></summary>
        [Column("store_id")] public short StoreId { get { return _StoreId; } set { _StoreId = value; MarkColumnModified("store_id"); } } short _StoreId;
        /// <summary></summary>
        [Column("active")] public bool Active { get { return _Active; } set { _Active = value; MarkColumnModified("active"); } } bool _Active;
        /// <summary></summary>
        [Column("username")] public string Username { get { return _Username; } set { _Username = value; MarkColumnModified("username"); } } string _Username;
        /// <summary></summary>
        [Column("password")] public string Password { get { return _Password; } set { _Password = value; MarkColumnModified("password"); } } string _Password;
        /// <summary></summary>
        [Column("last_update")] public DateTime LastUpdate { get { return _LastUpdate; } set { _LastUpdate = value; MarkColumnModified("last_update"); } } DateTime _LastUpdate;
        /// <summary></summary>
        [Column("picture")] public byte[] Picture { get { return _Picture; } set { _Picture = value; MarkColumnModified("picture"); } } byte[] _Picture;
    }

    /// <summary></summary>
    [TableName("store")]
    [PrimaryKey("store_id", AutoIncrement=true, SequenceName="store_store_id_seq")]
    [ExplicitColumns]
    public class Store: PetaPoco.PetaPocoRecord<Store>
    {
        /// <summary></summary>
        [Column("store_id")] public int StoreId { get { return _StoreId; } set { _StoreId = value; MarkColumnModified("store_id"); } } int _StoreId;
        /// <summary></summary>
        [Column("manager_staff_id")] public short ManagerStaffId { get { return _ManagerStaffId; } set { _ManagerStaffId = value; MarkColumnModified("manager_staff_id"); } } short _ManagerStaffId;
        /// <summary></summary>
        [Column("address_id")] public short AddressId { get { return _AddressId; } set { _AddressId = value; MarkColumnModified("address_id"); } } short _AddressId;
        /// <summary></summary>
        [Column("last_update")] public DateTime LastUpdate { get { return _LastUpdate; } set { _LastUpdate = value; MarkColumnModified("last_update"); } } DateTime _LastUpdate;
    }

    /// <summary>テストテーブル - オートナンバー</summary>
    [TableName("test_auto_number")]
    [PrimaryKey("key03", AutoIncrement=true, SequenceName="test_sequence01")]
    [ExplicitColumns]
    public class TestAutoNumber: PetaPoco.PetaPocoRecord<TestAutoNumber>
    {
        /// <summary>プライマリキー</summary>
        [Column("key03")] public int Key03 { get { return _Key03; } set { _Key03 = value; MarkColumnModified("key03"); } } int _Key03;
        /// <summary>bool型の列</summary>
        [Column("col_bool")] public bool ColBool { get { return _ColBool; } set { _ColBool = value; MarkColumnModified("col_bool"); } } bool _ColBool;
        /// <summary>int型の列</summary>
        [Column("col_int")] public int? ColInt { get { return _ColInt; } set { _ColInt = value; MarkColumnModified("col_int"); } } int? _ColInt;
        /// <summary>decimal型の列</summary>
        [Column("col_dec")] public decimal? ColDec { get { return _ColDec; } set { _ColDec = value; MarkColumnModified("col_dec"); } } decimal? _ColDec;
        /// <summary>varchar型の列</summary>
        [Column("col_varchar")] public string ColVarchar { get { return _ColVarchar; } set { _ColVarchar = value; MarkColumnModified("col_varchar"); } } string _ColVarchar;
        /// <summary>作成者</summary>
        [Column("create_by")] public string CreateBy { get { return _CreateBy; } set { _CreateBy = value; MarkColumnModified("create_by"); } } string _CreateBy;
        /// <summary>作成日時</summary>
        [Column("create_dt")] public DateTime CreateDt { get { return _CreateDt; } set { _CreateDt = value; MarkColumnModified("create_dt"); } } DateTime _CreateDt;
        /// <summary>更新者</summary>
        [Column("update_by")] public string UpdateBy { get { return _UpdateBy; } set { _UpdateBy = value; MarkColumnModified("update_by"); } } string _UpdateBy;
        /// <summary>更新日時</summary>
        [Column("update_dt")] public DateTime UpdateDt { get { return _UpdateDt; } set { _UpdateDt = value; MarkColumnModified("update_dt"); } } DateTime _UpdateDt;
    }

    /// <summary>テストテーブル - 複合キー</summary>
    [TableName("test_composite_key")]
    [PrimaryKey("key01,key02", AutoIncrement=false)]
    [ExplicitColumns]
    public class TestCompositeKey: PetaPoco.PetaPocoRecord<TestCompositeKey>
    {
        /// <summary>プライマリキーその１</summary>
        [Column("key01")] public string Key01 { get { return _Key01; } set { _Key01 = value; MarkColumnModified("key01"); } } string _Key01;
        /// <summary>プライマリキーその２</summary>
        [Column("key02")] public int Key02 { get { return _Key02; } set { _Key02 = value; MarkColumnModified("key02"); } } int _Key02;
        /// <summary>bool型の列</summary>
        [Column("col_bool")] public bool ColBool { get { return _ColBool; } set { _ColBool = value; MarkColumnModified("col_bool"); } } bool _ColBool;
        /// <summary>int型の列</summary>
        [Column("col_int")] public int? ColInt { get { return _ColInt; } set { _ColInt = value; MarkColumnModified("col_int"); } } int? _ColInt;
        /// <summary>decimal型の列</summary>
        [Column("col_dec")] public decimal? ColDec { get { return _ColDec; } set { _ColDec = value; MarkColumnModified("col_dec"); } } decimal? _ColDec;
        /// <summary>varchar型の列</summary>
        [Column("col_varchar")] public string ColVarchar { get { return _ColVarchar; } set { _ColVarchar = value; MarkColumnModified("col_varchar"); } } string _ColVarchar;
        /// <summary>作成者</summary>
        [Column("create_by")] public string CreateBy { get { return _CreateBy; } set { _CreateBy = value; MarkColumnModified("create_by"); } } string _CreateBy;
        /// <summary>作成日時</summary>
        [Column("create_dt")] public DateTime CreateDt { get { return _CreateDt; } set { _CreateDt = value; MarkColumnModified("create_dt"); } } DateTime _CreateDt;
        /// <summary>更新者</summary>
        [Column("update_by")] public string UpdateBy { get { return _UpdateBy; } set { _UpdateBy = value; MarkColumnModified("update_by"); } } string _UpdateBy;
        /// <summary>更新日時</summary>
        [Column("update_dt")] public DateTime UpdateDt { get { return _UpdateDt; } set { _UpdateDt = value; MarkColumnModified("update_dt"); } } DateTime _UpdateDt;
    }

    /// <summary></summary>
    [TableName("actor_info")]
    [ExplicitColumns]
    public class ActorInfo
    {
        /// <summary></summary>
        [Column("actor_id")] public int? ActorId { get; set; }
        /// <summary></summary>
        [Column("first_name")] public string FirstName { get; set; }
        /// <summary></summary>
        [Column("last_name")] public string LastName { get; set; }
        /// <summary></summary>
        [Column("film_info")] public string FilmInfo { get; set; }
    }

    /// <summary></summary>
    [TableName("customer_list")]
    [ExplicitColumns]
    public class CustomerList
    {
        /// <summary></summary>
        [Column("id")] public int? Id { get; set; }
        /// <summary></summary>
        [Column("name")] public string Name { get; set; }
        /// <summary></summary>
        [Column("address")] public string Address { get; set; }
        /// <summary></summary>
        [Column("zip code")] public string ZipCode { get; set; }
        /// <summary></summary>
        [Column("phone")] public string Phone { get; set; }
        /// <summary></summary>
        [Column("city")] public string City { get; set; }
        /// <summary></summary>
        [Column("country")] public string Country { get; set; }
        /// <summary></summary>
        [Column("notes")] public string Notes { get; set; }
        /// <summary></summary>
        [Column("sid")] public short? Sid { get; set; }
    }

    /// <summary></summary>
    [TableName("film_list")]
    [ExplicitColumns]
    public class FilmList
    {
        /// <summary></summary>
        [Column("fid")] public int? Fid { get; set; }
        /// <summary></summary>
        [Column("title")] public string Title { get; set; }
        /// <summary></summary>
        [Column("description")] public string Description { get; set; }
        /// <summary></summary>
        [Column("category")] public string Category { get; set; }
        /// <summary></summary>
        [Column("price")] public decimal? Price { get; set; }
        /// <summary></summary>
        [Column("length")] public short? Length { get; set; }
        /// <summary></summary>
        [Column("rating")] public string Rating { get; set; }
        /// <summary></summary>
        [Column("actors")] public string Actors { get; set; }
    }

    /// <summary></summary>
    [TableName("nicer_but_slower_film_list")]
    [ExplicitColumns]
    public class NicerButSlowerFilmList
    {
        /// <summary></summary>
        [Column("fid")] public int? Fid { get; set; }
        /// <summary></summary>
        [Column("title")] public string Title { get; set; }
        /// <summary></summary>
        [Column("description")] public string Description { get; set; }
        /// <summary></summary>
        [Column("category")] public string Category { get; set; }
        /// <summary></summary>
        [Column("price")] public decimal? Price { get; set; }
        /// <summary></summary>
        [Column("length")] public short? Length { get; set; }
        /// <summary></summary>
        [Column("rating")] public string Rating { get; set; }
        /// <summary></summary>
        [Column("actors")] public string Actors { get; set; }
    }

    /// <summary></summary>
    [TableName("sales_by_film_category")]
    [ExplicitColumns]
    public class SalesByFilmCategory
    {
        /// <summary></summary>
        [Column("category")] public string Category { get; set; }
        /// <summary></summary>
        [Column("total_sales")] public decimal? TotalSales { get; set; }
    }

    /// <summary></summary>
    [TableName("sales_by_store")]
    [ExplicitColumns]
    public class SalesByStore
    {
        /// <summary></summary>
        [Column("store")] public string Store { get; set; }
        /// <summary></summary>
        [Column("manager")] public string Manager { get; set; }
        /// <summary></summary>
        [Column("total_sales")] public decimal? TotalSales { get; set; }
    }

    /// <summary></summary>
    [TableName("staff_list")]
    [ExplicitColumns]
    public class StaffList
    {
        /// <summary></summary>
        [Column("id")] public int? Id { get; set; }
        /// <summary></summary>
        [Column("name")] public string Name { get; set; }
        /// <summary></summary>
        [Column("address")] public string Address { get; set; }
        /// <summary></summary>
        [Column("zip code")] public string ZipCode { get; set; }
        /// <summary></summary>
        [Column("phone")] public string Phone { get; set; }
        /// <summary></summary>
        [Column("city")] public string City { get; set; }
        /// <summary></summary>
        [Column("country")] public string Country { get; set; }
        /// <summary></summary>
        [Column("sid")] public short? Sid { get; set; }
    }
}


