
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String:      `server=192.168.1.212;uid=testman;pwd=**zapped**;database=employees;SslMode=None;`
//     Provider:               `MySql.Data.MySqlClient`
//     Schema:                 ``
//     Include Views:          `True`
//     Genetated:              `2020/02/24 16:22:27`

using System;
using PetaPoco;

namespace PetaPoco4Core.Database.Employees
{
    /// <summary>
    /// employees 接続文字列
    /// </summary>
    public static class Config
    {
        /// <summary>デフォルトの接続文字列</summary>
        public static string ConnectionString { get; set; }
    }

    /// <summary>
    /// employees Database Object
    /// </summary>
    public class DB : DatabaseExtension
    {
        /// <summary>
        /// employees Database Object
        /// </summary>
        public DB() : base(Config.ConnectionString, "MySql.Data.MySqlClient")
        {
        }
    }


    /// <summary></summary>
    [TableName("departments")]
    [PrimaryKey("dept_no", AutoIncrement=false)]
    [ExplicitColumns]
    public class department: PetaPoco.PetaPocoRecord<department>
    {
        /// <summary></summary>
        [Column] public string dept_no { get { return _dept_no; } set { _dept_no = value; MarkColumnModified("dept_no"); } } string _dept_no;
        /// <summary></summary>
        [Column] public string dept_name { get { return _dept_name; } set { _dept_name = value; MarkColumnModified("dept_name"); } } string _dept_name;
    }

    /// <summary></summary>
    [TableName("dept_emp")]
    [PrimaryKey("emp_no,dept_no", AutoIncrement=false)]
    [ExplicitColumns]
    public class dept_emp: PetaPoco.PetaPocoRecord<dept_emp>
    {
        /// <summary></summary>
        [Column] public int emp_no { get { return _emp_no; } set { _emp_no = value; MarkColumnModified("emp_no"); } } int _emp_no;
        /// <summary></summary>
        [Column] public string dept_no { get { return _dept_no; } set { _dept_no = value; MarkColumnModified("dept_no"); } } string _dept_no;
        /// <summary></summary>
        [Column] public DateTime from_date { get { return _from_date; } set { _from_date = value; MarkColumnModified("from_date"); } } DateTime _from_date;
        /// <summary></summary>
        [Column] public DateTime to_date { get { return _to_date; } set { _to_date = value; MarkColumnModified("to_date"); } } DateTime _to_date;
    }

    /// <summary></summary>
    [TableName("dept_manager")]
    [PrimaryKey("emp_no,dept_no", AutoIncrement=false)]
    [ExplicitColumns]
    public class dept_manager: PetaPoco.PetaPocoRecord<dept_manager>
    {
        /// <summary></summary>
        [Column] public int emp_no { get { return _emp_no; } set { _emp_no = value; MarkColumnModified("emp_no"); } } int _emp_no;
        /// <summary></summary>
        [Column] public string dept_no { get { return _dept_no; } set { _dept_no = value; MarkColumnModified("dept_no"); } } string _dept_no;
        /// <summary></summary>
        [Column] public DateTime from_date { get { return _from_date; } set { _from_date = value; MarkColumnModified("from_date"); } } DateTime _from_date;
        /// <summary></summary>
        [Column] public DateTime to_date { get { return _to_date; } set { _to_date = value; MarkColumnModified("to_date"); } } DateTime _to_date;
    }

    /// <summary></summary>
    [TableName("employees")]
    [PrimaryKey("emp_no", AutoIncrement=false)]
    [ExplicitColumns]
    public class employee: PetaPoco.PetaPocoRecord<employee>
    {
        /// <summary></summary>
        [Column] public int emp_no { get { return _emp_no; } set { _emp_no = value; MarkColumnModified("emp_no"); } } int _emp_no;
        /// <summary></summary>
        [Column] public DateTime birth_date { get { return _birth_date; } set { _birth_date = value; MarkColumnModified("birth_date"); } } DateTime _birth_date;
        /// <summary></summary>
        [Column] public string first_name { get { return _first_name; } set { _first_name = value; MarkColumnModified("first_name"); } } string _first_name;
        /// <summary></summary>
        [Column] public string last_name { get { return _last_name; } set { _last_name = value; MarkColumnModified("last_name"); } } string _last_name;
        /// <summary></summary>
        [Column] public string gender { get { return _gender; } set { _gender = value; MarkColumnModified("gender"); } } string _gender;
        /// <summary></summary>
        [Column] public DateTime hire_date { get { return _hire_date; } set { _hire_date = value; MarkColumnModified("hire_date"); } } DateTime _hire_date;
    }

    /// <summary></summary>
    [TableName("salaries")]
    [PrimaryKey("emp_no,from_date", AutoIncrement=false)]
    [ExplicitColumns]
    public class salary: PetaPoco.PetaPocoRecord<salary>
    {
        /// <summary></summary>
        [Column] public int emp_no { get { return _emp_no; } set { _emp_no = value; MarkColumnModified("emp_no"); } } int _emp_no;
        /// <summary></summary>
        [Column("salary")] public int _salary { get { return __salary; } set { __salary = value; MarkColumnModified("salary"); } } int __salary;
        /// <summary></summary>
        [Column] public DateTime from_date { get { return _from_date; } set { _from_date = value; MarkColumnModified("from_date"); } } DateTime _from_date;
        /// <summary></summary>
        [Column] public DateTime to_date { get { return _to_date; } set { _to_date = value; MarkColumnModified("to_date"); } } DateTime _to_date;
    }

    /// <summary>テストテーブル - オートナンバー</summary>
    [TableName("TestAutoNumber")]
    [PrimaryKey("Key03", AutoIncrement=true)]
    [ExplicitColumns]
    public class TestAutoNumber: PetaPoco.PetaPocoRecord<TestAutoNumber>
    {
        /// <summary>プライマリキー</summary>
        [Column] public int Key03 { get { return _Key03; } set { _Key03 = value; MarkColumnModified("Key03"); } } int _Key03;
        /// <summary>bool型の列</summary>
        [Column] public bool ColBool { get { return _ColBool; } set { _ColBool = value; MarkColumnModified("ColBool"); } } bool _ColBool;
        /// <summary>int型の列</summary>
        [Column] public int? ColInt { get { return _ColInt; } set { _ColInt = value; MarkColumnModified("ColInt"); } } int? _ColInt;
        /// <summary>decimal型の列</summary>
        [Column] public decimal? ColDec { get { return _ColDec; } set { _ColDec = value; MarkColumnModified("ColDec"); } } decimal? _ColDec;
        /// <summary>varchar型の列</summary>
        [Column] public string ColVarchar { get { return _ColVarchar; } set { _ColVarchar = value; MarkColumnModified("ColVarchar"); } } string _ColVarchar;
        /// <summary>作成者</summary>
        [Column] public string CreateBy { get { return _CreateBy; } set { _CreateBy = value; MarkColumnModified("CreateBy"); } } string _CreateBy;
        /// <summary>作成日時</summary>
        [Column] public DateTime CreateDt { get { return _CreateDt; } set { _CreateDt = value; MarkColumnModified("CreateDt"); } } DateTime _CreateDt;
        /// <summary>更新者</summary>
        [Column] public string UpdateBy { get { return _UpdateBy; } set { _UpdateBy = value; MarkColumnModified("UpdateBy"); } } string _UpdateBy;
        /// <summary>更新日時</summary>
        [Column] public DateTime UpdateDt { get { return _UpdateDt; } set { _UpdateDt = value; MarkColumnModified("UpdateDt"); } } DateTime _UpdateDt;
    }

    /// <summary>テストテーブル - 複合キー</summary>
    [TableName("TestCompositeKey")]
    [PrimaryKey("Key01,Key02", AutoIncrement=false)]
    [ExplicitColumns]
    public class TestCompositeKey: PetaPoco.PetaPocoRecord<TestCompositeKey>
    {
        /// <summary>プライマリキーその１</summary>
        [Column] public string Key01 { get { return _Key01; } set { _Key01 = value; MarkColumnModified("Key01"); } } string _Key01;
        /// <summary>プライマリキーその２</summary>
        [Column] public int Key02 { get { return _Key02; } set { _Key02 = value; MarkColumnModified("Key02"); } } int _Key02;
        /// <summary>bool型の列</summary>
        [Column] public bool ColBool { get { return _ColBool; } set { _ColBool = value; MarkColumnModified("ColBool"); } } bool _ColBool;
        /// <summary>int型の列</summary>
        [Column] public int? ColInt { get { return _ColInt; } set { _ColInt = value; MarkColumnModified("ColInt"); } } int? _ColInt;
        /// <summary>decimal型の列</summary>
        [Column] public decimal? ColDec { get { return _ColDec; } set { _ColDec = value; MarkColumnModified("ColDec"); } } decimal? _ColDec;
        /// <summary>varchar型の列</summary>
        [Column] public string ColVarchar { get { return _ColVarchar; } set { _ColVarchar = value; MarkColumnModified("ColVarchar"); } } string _ColVarchar;
        /// <summary>作成者</summary>
        [Column] public string CreateBy { get { return _CreateBy; } set { _CreateBy = value; MarkColumnModified("CreateBy"); } } string _CreateBy;
        /// <summary>作成日時</summary>
        [Column] public DateTime CreateDt { get { return _CreateDt; } set { _CreateDt = value; MarkColumnModified("CreateDt"); } } DateTime _CreateDt;
        /// <summary>更新者</summary>
        [Column] public string UpdateBy { get { return _UpdateBy; } set { _UpdateBy = value; MarkColumnModified("UpdateBy"); } } string _UpdateBy;
        /// <summary>更新日時</summary>
        [Column] public DateTime UpdateDt { get { return _UpdateDt; } set { _UpdateDt = value; MarkColumnModified("UpdateDt"); } } DateTime _UpdateDt;
    }

    /// <summary></summary>
    [TableName("titles")]
    [PrimaryKey("emp_no,title,from_date", AutoIncrement=false)]
    [ExplicitColumns]
    public class title: PetaPoco.PetaPocoRecord<title>
    {
        /// <summary></summary>
        [Column] public int emp_no { get { return _emp_no; } set { _emp_no = value; MarkColumnModified("emp_no"); } } int _emp_no;
        /// <summary></summary>
        [Column("title")] public string _title { get { return __title; } set { __title = value; MarkColumnModified("title"); } } string __title;
        /// <summary></summary>
        [Column] public DateTime from_date { get { return _from_date; } set { _from_date = value; MarkColumnModified("from_date"); } } DateTime _from_date;
        /// <summary></summary>
        [Column] public DateTime? to_date { get { return _to_date; } set { _to_date = value; MarkColumnModified("to_date"); } } DateTime? _to_date;
    }

    /// <summary>VIEW</summary>
    [TableName("current_dept_emp")]
    [ExplicitColumns]
    public class current_dept_emp
    {
        /// <summary></summary>
        [Column] public int emp_no { get; set; }
        /// <summary></summary>
        [Column] public string dept_no { get; set; }
        /// <summary></summary>
        [Column] public DateTime? from_date { get; set; }
        /// <summary></summary>
        [Column] public DateTime? to_date { get; set; }
    }

    /// <summary>VIEW</summary>
    [TableName("dept_emp_latest_date")]
    [ExplicitColumns]
    public class dept_emp_latest_date
    {
        /// <summary></summary>
        [Column] public int emp_no { get; set; }
        /// <summary></summary>
        [Column] public DateTime? from_date { get; set; }
        /// <summary></summary>
        [Column] public DateTime? to_date { get; set; }
    }
}


