
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String:      `Data Source=CentOSdb@Scott;User Id=SCOTT;Password=**zapped**;Pooling=true;`
//     Provider:               `Oracle.DataAccess.Client`
//     Schema:                 ``
//     Include Views:          `False`
//     Genetated:              `2020/02/24 02:08:13`

using System;
using PetaPoco;

namespace PetaPoco4Core.Database.Scoot
{
    /// <summary>
    /// Scott 接続文字列
    /// </summary>
    public static class Config
    {
        /// <summary>デフォルトの接続文字列</summary>
        public static string ConnectionString { get; set; }
    }

    /// <summary>
    /// Scott Database Object
    /// </summary>
    public class DB : DatabaseExtension
    {
        /// <summary>
        /// Scott Database Object
        /// </summary>
        public DB() : base(Config.ConnectionString, "Oracle.DataAccess.Client")
        {
        }
    }


    /// <summary></summary>
    [TableName("BONUS")]
    [ExplicitColumns]
    public class Bonu: PetaPoco.PetaPocoRecord<Bonu>
    {
        /// <summary></summary>
        [Column("ENAME")] public string Ename { get { return _Ename; } set { _Ename = value; MarkColumnModified("ENAME"); } } string _Ename;
        /// <summary></summary>
        [Column("JOB")] public string Job { get { return _Job; } set { _Job = value; MarkColumnModified("JOB"); } } string _Job;
        /// <summary></summary>
        [Column("SAL")] public decimal? Sal { get { return _Sal; } set { _Sal = value; MarkColumnModified("SAL"); } } decimal? _Sal;
        /// <summary></summary>
        [Column("COMM")] public decimal? Comm { get { return _Comm; } set { _Comm = value; MarkColumnModified("COMM"); } } decimal? _Comm;
    }

    /// <summary></summary>
    [TableName("DEPT")]
    [PrimaryKey("DEPTNO", AutoIncrement=false)]
    [ExplicitColumns]
    public class Dept: PetaPoco.PetaPocoRecord<Dept>
    {
        /// <summary></summary>
        [Column("DEPTNO")] public decimal Deptno { get { return _Deptno; } set { _Deptno = value; MarkColumnModified("DEPTNO"); } } decimal _Deptno;
        /// <summary></summary>
        [Column("DNAME")] public string Dname { get { return _Dname; } set { _Dname = value; MarkColumnModified("DNAME"); } } string _Dname;
        /// <summary></summary>
        [Column("LOC")] public string Loc { get { return _Loc; } set { _Loc = value; MarkColumnModified("LOC"); } } string _Loc;
    }

    /// <summary></summary>
    [TableName("EMP")]
    [PrimaryKey("EMPNO", AutoIncrement=false)]
    [ExplicitColumns]
    public class Emp: PetaPoco.PetaPocoRecord<Emp>
    {
        /// <summary></summary>
        [Column("EMPNO")] public decimal Empno { get { return _Empno; } set { _Empno = value; MarkColumnModified("EMPNO"); } } decimal _Empno;
        /// <summary></summary>
        [Column("ENAME")] public string Ename { get { return _Ename; } set { _Ename = value; MarkColumnModified("ENAME"); } } string _Ename;
        /// <summary></summary>
        [Column("JOB")] public string Job { get { return _Job; } set { _Job = value; MarkColumnModified("JOB"); } } string _Job;
        /// <summary></summary>
        [Column("MGR")] public decimal? Mgr { get { return _Mgr; } set { _Mgr = value; MarkColumnModified("MGR"); } } decimal? _Mgr;
        /// <summary></summary>
        [Column("HIREDATE")] public DateTime? Hiredate { get { return _Hiredate; } set { _Hiredate = value; MarkColumnModified("HIREDATE"); } } DateTime? _Hiredate;
        /// <summary></summary>
        [Column("SAL")] public decimal? Sal { get { return _Sal; } set { _Sal = value; MarkColumnModified("SAL"); } } decimal? _Sal;
        /// <summary></summary>
        [Column("COMM")] public decimal? Comm { get { return _Comm; } set { _Comm = value; MarkColumnModified("COMM"); } } decimal? _Comm;
        /// <summary></summary>
        [Column("DEPTNO")] public decimal? Deptno { get { return _Deptno; } set { _Deptno = value; MarkColumnModified("DEPTNO"); } } decimal? _Deptno;
    }

    /// <summary></summary>
    [TableName("SALGRADE")]
    [ExplicitColumns]
    public class Salgrade: PetaPoco.PetaPocoRecord<Salgrade>
    {
        /// <summary></summary>
        [Column("GRADE")] public decimal? Grade { get { return _Grade; } set { _Grade = value; MarkColumnModified("GRADE"); } } decimal? _Grade;
        /// <summary></summary>
        [Column("LOSAL")] public decimal? Losal { get { return _Losal; } set { _Losal = value; MarkColumnModified("LOSAL"); } } decimal? _Losal;
        /// <summary></summary>
        [Column("HISAL")] public decimal? Hisal { get { return _Hisal; } set { _Hisal = value; MarkColumnModified("HISAL"); } } decimal? _Hisal;
    }

    /// <summary>テストテーブルほげ</summary>
    [TableName("TEST_HOGE")]
    [PrimaryKey("KEY01,KEY02", AutoIncrement=false)]
    [ExplicitColumns]
    public class TestHoge: PetaPoco.PetaPocoRecord<TestHoge>
    {
        /// <summary>プライマリキー その１</summary>
        [Column("KEY01")] public string Key01 { get { return _Key01; } set { _Key01 = value; MarkColumnModified("KEY01"); } } string _Key01;
        /// <summary>プライマリキー その２</summary>
        [Column("KEY02")] public decimal Key02 { get { return _Key02; } set { _Key02 = value; MarkColumnModified("KEY02"); } } decimal _Key02;
        /// <summary>bool型の列</summary>
        [Column("COL_BOOL")] public decimal ColBool { get { return _ColBool; } set { _ColBool = value; MarkColumnModified("COL_BOOL"); } } decimal _ColBool;
        /// <summary>int型の列</summary>
        [Column("COL_INT")] public decimal? ColInt { get { return _ColInt; } set { _ColInt = value; MarkColumnModified("COL_INT"); } } decimal? _ColInt;
        /// <summary>decimal型の列</summary>
        [Column("COL_DEC")] public decimal? ColDec { get { return _ColDec; } set { _ColDec = value; MarkColumnModified("COL_DEC"); } } decimal? _ColDec;
        /// <summary>文字列型の列</summary>
        [Column("COL_VARCHAR")] public string ColVarchar { get { return _ColVarchar; } set { _ColVarchar = value; MarkColumnModified("COL_VARCHAR"); } } string _ColVarchar;
        /// <summary>作成者</summary>
        [Column("CREATE_BY")] public string CreateBy { get { return _CreateBy; } set { _CreateBy = value; MarkColumnModified("CREATE_BY"); } } string _CreateBy;
        /// <summary>作成日時</summary>
        [Column("CREATE_DT")] public DateTime CreateDt { get { return _CreateDt; } set { _CreateDt = value; MarkColumnModified("CREATE_DT"); } } DateTime _CreateDt;
        /// <summary>更新者</summary>
        [Column("UPDATE_BY")] public string UpdateBy { get { return _UpdateBy; } set { _UpdateBy = value; MarkColumnModified("UPDATE_BY"); } } string _UpdateBy;
        /// <summary>更新日時</summary>
        [Column("UPDATE_DT")] public DateTime UpdateDt { get { return _UpdateDt; } set { _UpdateDt = value; MarkColumnModified("UPDATE_DT"); } } DateTime _UpdateDt;
    }
}


